CREATE DATABASE IF NOT EXISTS concesionaria_db;
CREATE DATABASE IF NOT EXISTS vehiculos_db;
CREATE DATABASE IF NOT EXISTS clientes_db;
CREATE DATABASE IF NOT EXISTS ventas_db;
CREATE DATABASE IF NOT EXISTS servicios_db;
